# -*- coding: cp1250 -*-
print("Gyártó: Kovács Patrik")
print("@        @")
print(" @      @")
print(" @      @")
print(" @      @")
print(" @      @")
print("  @@  @@")
print("    @@")
print("    @@")
print("    @@")
print("    @@")
print(" @@@@@@@@")
print(1,2,3,4,5)
emd = ___
